name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ChallengeNet.API
    - name: Build
      run: dotnet build ChallengeNet.API --no-restore
    - name: Test
      run: dotnet test ChallengeNet.Test --no-build --verbosity normal
